///////////////////////////////////////////////////////////////////////////////
// Untitled1Services.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Untitled1 = 0x3F000000;
#define SRVNAME_UNTITLED1 "Untitled1"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_Untitled1CModule1 = {0xd05d5aa5,0x4149,0x4c00,{0xa1,0x51,0x68,0xd6,0x30,0x8f,0x00,0x0f}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_Module1DefaultAdsPort = 0x00000001;
const PTCID PID_Module1Counter = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Module1Inputs
{
	LONG PosInc_L;
	LONG PosInc_R;
	LONG VelAct_L;
	LONG VelAct_R;
	float torque_raw;
	SHORT sEMG_ch1;
	SHORT sEMG_ch2;
} Module1Inputs, *PModule1Inputs;

typedef struct _Module1Outputs
{
	USHORT Controlword_L;
	USHORT Controlword_R;
	SHORT target_torque_L;
	SHORT target_torque_R;
} Module1Outputs, *PModule1Outputs;

typedef struct _Module1ADSOUT
{
	float Pos_L;
	float Pos_R;
	float Vel_rads_L;
	float Vel_rads_R;
	float torque_raw;
	float sEMG_Ch1;
	float sEMG_Ch2;
} Module1ADSOUT, *PModule1ADSOUT;

typedef struct _Module1ADSIN
{
	USHORT Controlword_L;
	USHORT Controlword_R;
	SHORT Target_Torque_L;
	SHORT Target_Torque_R;
} Module1ADSIN, *PModule1ADSIN;

#pragma pack(push,1)
typedef struct _Module1variables
{
} Module1variables, *PModule1variables;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Module1Inputs 0
#define ADI_Module1Outputs 1
#define ADI_Module1ADSOUT 3
#define ADI_Module1ADSIN 4
#define ADI_Module1variables 5
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
